spring:
  application:
    name: Config-Default
server:
  port: 7090
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8765/eureka
